export class SolicitudesModel {
    constructor(
        public sp_id_proceso?: number,
        public sp_id_depto?: string,
        public sp_id_mun?: string,
        public sp_id_corporacion?: string,
        public sp_id_despacho?: string,
        public sp_demandante?: string,
        public sp_demandado?: string,
        public sp_radicacion?: number,
        public sp_juzgado?: string,
        public sp_rad_23?: string,
        public sp_tipo_proceso?: string,
        public sp_sus_ingreso?: string,
        public sp_operadores?: string,
        public sp_fecha_ingreso?: String,
        public sp_ingreso_monolegal?: number,
        public sp_ingreso_misprocesos?: number,
        public sp_descripcion?: string,
        public sp_tipo?: string,
        public sp_id_planilla?: string,
        public sp_etiqueta?: string,
        public sp_tramite?: string,
        public fecha?: String,
        public nameTipo?: string,
        public suscriptor?: string,
        public depto?: string,
        public mun?: string,
        public despacho?: string,
        public nameSuscriptor?: string,
    ) { }
}
